# Generated by Django 5.1 on 2025-03-15 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_address_location_alter_address_address1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('profile_image', models.URLField(blank=True, max_length=500)),
                ('profile_rounded_image', models.URLField(blank=True, max_length=500)),
                ('standard_logo', models.URLField(blank=True, max_length=500)),
                ('square_logo', models.URLField(blank=True, max_length=500)),
                ('background_colour', models.CharField(blank=True, max_length=50)),
                ('seller_type', models.CharField(blank=True, max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('seller_source', models.CharField(blank=True, max_length=50)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
