# Generated by Django 5.1 on 2025-03-18 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('locations', '0002_address_location_alter_address_address1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='available',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='profile_rounded_image',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='square_logo',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='standard_logo',
        ),
        migrations.AddField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the seller is active'),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='URL of the profile image', max_length=500),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_rounded_image_url',
            field=models.URLField(blank=True, help_text='URL of the rounded profile image', max_length=500),
        ),
        migrations.AddField(
            model_name='seller',
            name='square_logo_url',
            field=models.URLField(blank=True, help_text='URL of the square logo', max_length=500),
        ),
        migrations.AddField(
            model_name='seller',
            name='standard_logo_url',
            field=models.URLField(blank=True, help_text='URL of the standard logo', max_length=500),
        ),
        migrations.AddField(
            model_name='seller',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Address associated with the seller', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='background_colour',
            field=models.CharField(blank=True, help_text='Hex color code for UI branding', max_length=7),
        ),
        migrations.AlterField(
            model_name='seller',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch name if applicable', max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(help_text="Seller's full name or business name", max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.PositiveIntegerField(help_text='Scraped seller ID from daft.ie', unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_source',
            field=models.CharField(blank=True, help_text="Source of the seller (e.g., 'daft.ie')", max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(choices=[('BRANDED_AGENT', 'Branded Agent'), ('PRIVATE_USER', 'Private User'), ('UNBRANDED_AGENT', 'Unbranded Agent'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Type of seller', max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(default=1, help_text='The user associated with this seller', on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
