# Generated by Django 5.1 on 2025-03-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_remove_seller_available_remove_seller_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='seller',
            name='branch',
        ),
        migrations.AddField(
            model_name='seller',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company to which this seller belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.company'),
        ),
    ]
