# Generated by Django 5.1 on 2025-03-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_company_remove_seller_branch_seller_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.PositiveIntegerField(blank=True, help_text='Scraped seller ID from daft.ie', null=True, unique=True),
        ),
    ]
