# Generated by Django 5.1 on 2025-03-20 14:52

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_address_location_alter_address_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, max_length=2),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city', 'country'], name='locations_a_city_c5268f_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code'], name='locations_a_postal__efd86d_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['local_authority'], name='locations_a_local_a_c4a5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['location'], name='locations_a_locatio_2ed367_idx'),
        ),
    ]
